// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ADialog: typeof import('./components/ADialog.vue')['default']
    DDialog: typeof import('./components/DDialog.vue')['default']
    DLine: typeof import('./components/DLine.vue')['default']
    DPage: typeof import('./components/DPage.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    LoginScreen: typeof import('./components/LoginScreen.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    VrTable: typeof import('./components/VrTable.vue')['default']
  }
}

export { }
