// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADialog: typeof import('./components/ADialog.vue')['default']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    DDialog: typeof import('./components/DDialog.vue')['default']
    DLine: typeof import('./components/DLine.vue')['default']
    DPage: typeof import('./components/DPage.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    LoginScreen: typeof import('./components/LoginScreen.vue')['default']
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardSection: typeof import('quasar')['QCardSection']
    QDialog: typeof import('quasar')['QDialog']
    QFile: typeof import('quasar')['QFile']
    QForm: typeof import('quasar')['QForm']
    QIcon: typeof import('quasar')['QIcon']
    QInput: typeof import('quasar')['QInput']
    QSelect: typeof import('quasar')['QSelect']
    QTable: typeof import('quasar')['QTable']
    QToolbar: typeof import('quasar')['QToolbar']
    QToolbarTitle: typeof import('quasar')['QToolbarTitle']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    Tooth: typeof import('./components/tooth.vue')['default']
    VrTable: typeof import('./components/VrTable.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}

export { }
